Rails/baitaplon/config/routes.rb
Rails.application.routes.draw do
  resources :information
  # get 'home/index'
  get 'home/about'
  root 'home#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

Rails/baitaplon/app/models/create_inf.rb
class CreateInf < ApplicationRecord
end

Rails/baitaplon/app/models/information.rb
class Information < ApplicationRecord
end

Rails/baitaplon/app/models/user.rb
class User < ApplicationRecord
end

Rails/baitaplon/app/controllers/create_infs_controller.rb
class CreateInfsController < ApplicationController
  before_action :set_create_inf, only: %i[ show edit update destroy ]

  # GET /create_infs or /create_infs.json
  def index
    @create_infs = CreateInf.all
  end

  # GET /create_infs/1 or /create_infs/1.json
  def show
  end

  # GET /create_infs/new
  def new
    @create_inf = CreateInf.new
  end

  # GET /create_infs/1/edit
  def edit
  end

  # POST /create_infs or /create_infs.json
  def create
    @create_inf = CreateInf.new(create_inf_params)

    respond_to do |format|
      if @create_inf.save
        format.html { redirect_to create_inf_url(@create_inf), notice: "Create inf was successfully created." }
        format.json { render :show, status: :created, location: @create_inf }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @create_inf.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /create_infs/1 or /create_infs/1.json
  def update
    respond_to do |format|
      if @create_inf.update(create_inf_params)
        format.html { redirect_to create_inf_url(@create_inf), notice: "Create inf was successfully updated." }
        format.json { render :show, status: :ok, location: @create_inf }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @create_inf.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /create_infs/1 or /create_infs/1.json
  def destroy
    @create_inf.destroy

    respond_to do |format|
      format.html { redirect_to create_infs_url, notice: "Create inf was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_create_inf
      @create_inf = CreateInf.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def create_inf_params
      params.require(:create_inf).permit(:first_name, :last_name, :email, :phone, :twitter)
    end
end

Rails/baitaplon/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
  def about
  end
  
end

Rails/baitaplon/app/controllers/information_controller.rb
class InformationController < ApplicationController
  before_action :set_information, only: %i[ show edit update destroy ]

  # GET /information or /information.json
  def index
    @information = Information.all
  end

  # GET /information/1 or /information/1.json
  def show
  end

  # GET /information/new
  def new
    @information = Information.new
  end

  # GET /information/1/edit
  def edit
  end

  # POST /information or /information.json
  def create
    @information = Information.new(information_params)

    respond_to do |format|
      if @information.save
        format.html { redirect_to information_url(@information), notice: "Information was successfully created." }
        format.json { render :show, status: :created, location: @information }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @information.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /information/1 or /information/1.json
  def update
    respond_to do |format|
      if @information.update(information_params)
        format.html { redirect_to information_url(@information), notice: "Information was successfully updated." }
        format.json { render :show, status: :ok, location: @information }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @information.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /information/1 or /information/1.json
  def destroy
    @information.destroy

    respond_to do |format|
      format.html { redirect_to information_index_url, notice: "Information was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_information
      @information = Information.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def information_params
      params.require(:information).permit(:first_name, :lats_name, :email, :phone, :twitter)
    end
end

Rails/baitaplon/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]

  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to user_url(@user), notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to user_url(@user), notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:first_name, :last_name, :email, :phone, :twitter)
    end
end

Rails/baitaplon/app/helpers/create_infs_helper.rb
module CreateInfsHelper
end

Rails/baitaplon/app/helpers/information_helper.rb
module InformationHelper
end

Rails/baitaplon/app/helpers/users_helper.rb
module UsersHelper
end

Rails/baitaplon/app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
<%= link_to 'Baitaplon', root_path, class: "navbar-brand"  %>
  <%# <a class="navbar-brand" href="#">Baitaplon</a> %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      
      <li class="nav-item">
       <%= link_to 'About Us',  home_about_path, class: "nav-link" %>
        <%# <a class="nav-link" href="#">Link</a> %>
      </li>
      <li class="nav-item">
      <%= link_to 'Information', information_index_path, class: "nav-link" %>
        <%# <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a> %>
      </li>
      <%# <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Dropdown
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="#">Action</a>
          <a class="dropdown-item" href="#">Another action</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li> %>
      <%# <li class="nav-item">
        <a class="nav-link disabled" href="#">Disabled</a>
      </li> %>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>

Rails/baitaplon/app/views/home/about.html.erb
<H1> ABOUT US</H1>

Rails/baitaplon/app/views/information/_form.html.erb
<%= form_with(model: information) do |form| %>
  <% if information.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(information.errors.count, "error") %> prohibited this information from being saved:</h2>

      <ul>
        <% information.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class= "field form-group">
    <%= form.label :first_name, style: "display: block" %>
    <%= form.text_field :first_name %>
  </div>

  <div class= "field form-group">
    <%= form.label :lats_name, style: "display: block" %>
    <%= form.text_field :lats_name %>
  </div>

  <div class= "field form-group">
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email %>
  </div>

  <div class= "field form-group">
    <%= form.label :phone, style: "display: block" %>
    <%= form.text_field :phone %>
  </div>

  <div class= "field form-group">
    <%= form.label :twitter, style: "display: block" %>
    <%= form.text_field :twitter %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

Rails/baitaplon/app/views/information/_information.html.erb
<div id="<%= dom_id information %>">
  <p>
    <strong>First name:</strong>
    <%= information.first_name %>
  </p>

  <p>
    <strong>Lats name:</strong>
    <%= information.lats_name %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= information.email %>
  </p>

  <p>
    <strong>Phone:</strong>
    <%= information.phone %>
  </p>

  <p>
    <strong>Twitter:</strong>
    <%= information.twitter %>
  </p>

</div>

Rails/baitaplon/app/views/information/edit.html.erb
<h1>Editing information</h1>

<%= render "form", information: @information %>

<br>

<div>
  <%= link_to "Show this information", @information %> |
  <%= link_to "Back to information", information_index_path %>
</div>

Rails/baitaplon/app/views/information/index.html.erb
<p style="color: green">
  <%= notice %>
</p>

  <h1>Information</h1>
  <table class="table table-hover">
    <thead>
      <tr>
        <%# <th scope="col">id</th> %>
        <th scope="col">First name</th>
        <th scope="col">Last name</th>
        <th scope="col">Email</th>
        <th scope="col">Phone</th>
        <th scope="col">Twitter</th>
        <th colspan="3"></th>
      </tr>
    </thead>
    <tbody>
      <% @information.each do |information| %> 
      <tr>
        <%# <td cope="row"> <%= information.id %></td>
         <td cope="row"> <%= information.first_name %></td>
        <td cope="row"> <%= information.lats_name %></td>
         <td cope="row"> <%= information.email %></td>
         <td cope="row"> <%= information.phone %></td>
         <td cope="row"> <%= information.twitter %></td>
        <td>
          <%= link_to "Show" , information%>
        </td>
        <td>
          <%= link_to "Edit" , edit_information_path(information) %>
        </td>
        <td>
          <%= button_to "Delete" ,  information, method: :delete , class: "btn btn-primary" %>
        </td>
      </tr>
      <%# <tr>
        <th scope="row">2</th>
        <td>Tuong</td>
        <td>Nga</td>
        <td>nga@gmail.com</td>
        <td>123445677</td>
        <td>aggdb.tw</td>
          <td>
          <%= link_to "Show" , information_index_path %> 
        <%# </td>
        <td>
          <%= link_to "Edit" , edit_information_path(information) %>
        <%# </td>
        <td>
          <%= link_to "Delete" , information, method: :delete
        </td> %> 
      <%# </tr> %>
      <% end %>
    </tbody>
  </table>
  <%= link_to "New information" , new_information_path %>

Rails/baitaplon/app/views/information/new.html.erb
<h1>New information</h1>

<%= render "form", information: @information %>

<br>

<div>
  <%= link_to "Back to information", information_index_path %>
</div>

Rails/baitaplon/app/views/information/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @information %>

<div>
  <%= link_to "Edit this information", edit_information_path(@information) %> |
  <%= link_to "Back to information", information_index_path %>

  <%= button_to "Destroy this information", @information, method: :delete %>
</div>

Rails/baitaplon/app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <title>Bai tap lon</title>
     <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body>
   <%= render 'home/header' %>
    <div class= 'container'>
    <br/>
      <%= yield %>
  </div>
   

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>

Rails/baitaplon/app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :first_name, style: "display: block" %>
    <%= form.text_field :first_name %>
  </div>

  <div>
    <%= form.label :last_name, style: "display: block" %>
    <%= form.text_field :last_name %>
  </div>

  <div>
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email %>
  </div>

  <div>
    <%= form.label :phone, style: "display: block" %>
    <%= form.text_field :phone %>
  </div>

  <div>
    <%= form.label :twitter, style: "display: block" %>
    <%= form.text_field :twitter %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

Rails/baitaplon/app/views/users/_user.html.erb
<div id="<%= dom_id user %>">
  <p>
    <strong>First name:</strong>
    <%= user.first_name %>
  </p>

  <p>
    <strong>Last name:</strong>
    <%= user.last_name %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= user.email %>
  </p>

  <p>
    <strong>Phone:</strong>
    <%= user.phone %>
  </p>

  <p>
    <strong>Twitter:</strong>
    <%= user.twitter %>
  </p>

</div>

Rails/baitaplon/app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Show this user", @user %> |
  <%= link_to "Back to users", users_path %>
</div>

Rails/baitaplon/app/views/users/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Users</h1>

<div id="users">
  <% @users.each do |user| %>
    <%= render user %>
    <p>
      <%= link_to "Show this user", user %>
    </p>
  <% end %>
</div>

<%= link_to "New user", new_user_path %>

Rails/baitaplon/app/views/users/new.html.erb
<h1>New user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Back to users", users_path %>
</div>

Rails/baitaplon/app/views/users/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @user %>

<div>
  <%= link_to "Edit this user", edit_user_path(@user) %> |
  <%= link_to "Back to users", users_path %>

  <%= button_to "Destroy this user", @user, method: :delete %>
</div>